version: "3.8"
services:
  auditlogdb:
      image: mongo:latest
      container_name: auditlogdb
      restart: always
      ports:
        - "27017:27017"

  # auditlogbackend:
  #     build: 
  #       context: . 
  #       dockerfile: ./Dockerfile
  #     container_name: auditlogbackend
  #     restart: always
  #     ports:
  #       - "8080:80"
  #     depends_on:
  #       - auditlogdb
  