version: "3.8"
services:
  db:
      image: mongo:latest
      container_name: mongodb
      restart: always
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=<YOUR_PASSWORD>
      ports:
        - "27017:27017"